config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: "welcome#index"
  get 'welcome/about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'users/passwords',
  }

  resources :posts do
    member do
      get 'simple'
    end
  end

  namespace :admin do
    resources :users do
      resources :posts do
        member do 
          put 'change_status'
        end
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  helper WelcomeHelper
  
  def index
    @posts = Post.opened.recent.page(params[:page])
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def cache_key_for_public_posts
    count          = Post.count
    max_updated_at = Post.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "public-posts/all-#{count}-#{max_updated_at}"
  end
end

app/views/welcome/_ppt.html.haml
- posts.each do |post|
  .col-md-4
    = link_to image_tag(post.cover_page_url, {height: 220, width:320}), post_path(post)
    %p
    %p
      %a.btn.btn-default{:href => "http://www.facebook.com/sharer/sharer.php?u="+post_url(post) , :target => "_blank"} Facebook share      
      %a.btn.btn-default{:href => "http://www.linkedin.com/shareArticle?mini=true&url="+post_url(post), :role => "button"} Linkedin share
      = link_to 'QR', post.qr_image_path, class: ['btn', 'btn-default', 'btn-qrcode']
	  
	  
	  

app/views/welcome/about.html.haml
%br
%br
%br
.col-md-12
  .alert.alert-success About PPT
  .bs-callout.bs-callout-info
    %h4 1. Markdown fomart
    %p
      Write ppt with online editor in one file using
      = succeed "." do
        %code github flavor Markdown format.
  .bs-callout.bs-callout-info
    %h4 2. Left/right Paging
    %p
      Using line
      = succeed "." do
        %code ---
      in markdown file for left/right paging.
  .bs-callout.bs-callout-info
    %h4 3. Up/down paging
    %p
      Using line
      = succeed "." do
        %code --
      in markdown file for up/down paging.

  .highlight
    \# Sample: copy the follow code to your own ppt<br>

    \## this is the first page<br>
    \--<br>
    \### this is the page below the first page<br>
    \---<br>
    \## this is page at right of first page<br>


  .alert.alert-success About Options
  %table.table.table-striped.table-bordered
    %tr
      %th Display controls
      %td Whether to display controls bar
    %tr
      %th Display Progress Bar
      %td Whether to display progress bar at the bottom
    %tr
      %th Display Slide Page Number
      %td Whether to display page number
    %tr
      %th Push slide change to history
      %td If chosen, each slide is a different url, browser back can be used to retrival history.
    %tr
      %th Enable keyboard
      %td Whether keyboard is enabled to control slides.
    %tr
      %th Vertical Centering of Slides
      %td Slides locates in vertical center, or it will locates in vertical top.
    %tr
      %th Loop the Presentation
      %td If the presentation loop when goes to the end.
    %tr
      %th Stop Auto-sliding After Input
      %td When Auto-sliding mode enabled, whether it can be stop by your input.
    %tr
      %th Enable Mouse Wheel
      %td Enable mouse wheel when presentation.
    %tr
      %th Hides Address on Mobile Devices
      %td Hides address bar on mobile devices or not.
    %tr
      %th Auto Slide Time
      %td Mills seconds. when set to 0, means no auto sliding.
    %tr
      %th Theme
      %td Theme of presentation, can be chosen from several template.
    %tr
      %th Transition style
      %td Slides transition styles.
    %tr
      %th Transition speed
      %td Slides transition speed.
    %tr
      %th Transition style for backgrounds
      %td Background transition style.
    %tr
      %th Parallax background image
      %td Background image url.
    %tr
      %th Parallax background size
      %td Background image size

app/views/welcome/index.html.haml
.jumbotron
  .container
    %br
    %br
    %br
    %h1 SlideMark
    %p= t('description')
    = link_to 'Try now', user_signed_in? ? new_admin_user_post_path(current_user) : new_user_session_path, class: [ 'btn', 'btn-primary', 'btn-lg'], role:['button']

- cache(cache_key_for_public_posts) do
  - if @posts.present?
    - @posts.each_slice(3) do |sub_posts|
      .container
        .row= render partial: 'ppt', locals: { posts: sub_posts}    
        %hr/

  %center= paginate @posts