config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: "welcome#index"
  get 'welcome/about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'users/passwords',
  }

  resources :posts do
    member do
      get 'simple'
    end
  end

  namespace :admin do
    resources :users do
      resources :posts do
        member do 
          put 'change_status'
        end
      end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  ST_OPEN = 1

  QR_SEED = 'Ting'
  QR_SIZE = 300

  SCREEN_SEED = 'Zhang'
  SCREEN_WIDTH = 320
  SCREEN_HEIGHT = 220

  after_save :screen_shot
  scope :recent , -> { order('created_at DESC') }
  scope :opened, -> { where(status: ST_OPEN) }
  #validates :title, presence: true
  validates :content, presence: true

  belongs_to :user

  def cover_page_path
    '/assets/images/screenshot/' + Digest::MD5.hexdigest(SCREEN_SEED + self.id.to_s) + '.png'
  end

  def simple
    return self.content.split(/^--/)[0] if self.content.present?
    return nil
  end

  def cover_page_url
    self.open? ? self.cover_page_path : '/assets/images/not_published.png'
  end

  def qr_image_path
    'assets/images/qrcode/' + Digest::MD5.hexdigest(QR_SEED + self.id.to_s) + '.png'
  end

  def open?
    self.status == ST_OPEN
  end

  def publish
    if self.update(status: ST_OPEN)
      qr_code
    end
  end

  private

    def post_root
      if Rails.env.development?
        '127.0.0.1:3000'
      else
        'http://www.slidemark.net'
      end
    end

    def screen_shot
      return unless self.open?
      system("/usr/local/bin/wkhtmltoimage --height #{SCREEN_HEIGHT} --width #{SCREEN_WIDTH} --format png #{post_root+ simple_post_path(self)} - > #{'public' + self.cover_page_path}")
      #kit = IMGKit.new(post_root+ post_path(self))
      #kit.to_file('public/' + self.cover_page_path)
    end

    def qr_code
      qr = RQRCode::QRCode.new(post_root + post_path(self), :size => 4, :level => :h )
      png = qr.to_img
      png.resize(QR_SIZE, QR_SIZE).save('public/' + self.qr_image_path)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  respond_to :html
  load_and_authorize_resource
  layout 'ppt', only: ['show']
  helper PostsHelper
  
  def index
    @posts = current_user.posts.recent.page(params[:page])
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new.decorate
  end

  def edit
    @post = @post.decorate
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id, title: 'dummy')).decorate
    if @post.save
      redirect_to admin_user_posts_url, flash: {notice: I18n.t('model.post.create.success')}
      return
    end
    render :new
  end

  def update
    @post = @post.decorate
    if @post.update(post_params)
      redirect_to edit_admin_user_post_url, flash: {notice: I18n.t('model.post.update.success')}
      return
    end
    render :edit
  end

  def change_status
    @post.publish
    redirect_to admin_user_posts_path, flash: {notice: I18n.t('model.post.publish.success')}
  end

  def destroy
    @post.destroy
    redirect_to admin_user_posts_path, flash: {notice: I18n.t('model.post.delete.success')}
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :status, :s_controls, :s_progress, :s_slideNumber,
        :s_history, :s_keyboard, :s_overview, :s_center, :s_loop, :s_rtl, :s_fragments, :s_embedded, :s_autoSlide,
        :s_autoSlideStoppable, :s_mouseWheel, :s_hideAddressBar, :s_previewLinks, :s_transition,
        :s_transitionSpeed, :s_backgroundTransition, :s_theme, :s_viewDistance,
        :s_parallaxBackgroundImage, :s_parallaxBackgroundSize)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html
  load_and_authorize_resource

  def index
    @posts = Post.recent.page(params[:page])
    respond_with(@posts)
  end

  def show
    render layout: 'ppt'
  end

  def simple
    render layout: 'simple'
  end

  def new
    @post = Post.new.decorate
    respond_with(@post)
  end

  def edit
    @post = @post.decorate
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id, title: 'dummy')).decorate
    if @post.save
      redirect_to posts_url, flash: {notice: I18n.t('model.post.create.success')}
      return
    end
    respond_with(@post)
  end

  def update
    @post = @post.decorate
    if @post.update(post_params)
      redirect_to edit_post_url, flash: {notice: I18n.t('model.post.update.success')}
      return
    end
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :s_controls, :s_progress, :s_slideNumber,
        :s_history, :s_keyboard, :s_overview, :s_center, :s_loop, :s_rtl, :s_fragments, :s_embedded, :s_autoSlide,
        :s_autoSlideStoppable, :s_mouseWheel, :s_hideAddressBar, :s_previewLinks, :s_transition,
        :s_transitionSpeed, :s_backgroundTransition, :s_theme, :s_viewDistance,
        :s_parallaxBackgroundImage, :s_parallaxBackgroundSize)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def cache_key_for_posts
    count          = Post.count
    max_updated_at = Post.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "posts/all-#{current_user.id}-#{count}-#{max_updated_at}"
  end

end

app/views/admin/posts/_form.html.haml
.editor-container
  -#.form-group
    = t.label :title, "#{t('model.post.title')}(*)", class: ['col-sm-1', 'control-label']
    .col-sm-8
      = t.text_field :title, value: utf8(@post.title), class: 'form-control', placeholder: 'Input title'
  .form-group
    = t.text_area :content, value: utf8(@post.content)
    #editor
    #panel
      .form-control     
        = t.check_box :s_controls
        = t.label :s_controls, " Display controls"
      .form-control 
        = t.check_box :s_progress
        = t.label :s_progress, "Display Progress Bar"
      .form-control 
        = t.check_box :s_slideNumber
        = t.label :s_slideNumber, "Display Slide Page Number"
      .form-control 
        = t.check_box :s_history
        = t.label :s_history, "Push slide change to history"
      .form-control 
        = t.check_box :s_keyboard
        = t.label :s_keyboard, "Enable keyboard"
      -#.form-control 
        = t.check_box :s_overview
        = t.label :s_overview, "Enable Slide Overview "
      .form-control 
        = t.check_box :s_center
        = t.label :s_center, "Vertical Centering of Slides"
      .form-control 
        = t.check_box :s_loop
        = t.label :s_loop, "Loop the Presentation"
      -#.form-control 
        = t.check_box :s_rtl
        = t.label :s_rtl, "Change to be RTL"
      -#.form-control 
        = t.check_box :s_fragments
        = t.label :s_fragments, "Turns fragments on"
      -#.form-control 
        = t.check_box :s_embedded
        = t.label :s_embedded, "Embedded mode,"
      .form-control 
        = t.check_box :s_autoSlideStoppable
        = t.label :s_autoSlideStoppable, "Stop Auto-sliding After Input"
      .form-control 
        = t.check_box :s_mouseWheel
        = t.label :s_mouseWheel, "Enable Mouse Wheel"
      .form-control 
        = t.check_box :s_hideAddressBar
        = t.label :s_hideAddressBar, "Hides Address on Mobile Devices"
      -#.form-control 
        = t.check_box :s_previewLinks
        = t.label :s_previewLinks, "Opens Links in Iframe Preview"
      -#.div 
        = t.label :s_viewDistance, "Number of Visible Slides"
        = t.number_field :s_viewDistance, default: 3, class: 'form-control'
      .div 
        = t.label :s_autoSlide, "Auto Slide Time(millisecond)"
        = t.number_field :s_autoSlide, default: 0, class: 'form-control'
      %div
        = t.label :s_theme, "Theme"
        = t.select :s_theme, @post.theme_select, {default: "default"}, class: 'form-control'
      %div
        = t.label :s_transition, "Transition style"
        = t.select :s_transition, @post.transition_select, {default: "default"},  class: 'form-control'
      %div
        = t.label :s_transitionSpeed, "Transition speed"
        = t.select :s_transitionSpeed, @post.transition_speed_select, {default: "default"},  class: 'form-control'
      %div
        = t.label :s_backgroundTransition, "Transition style for backgrounds"
        = t.select :s_backgroundTransition, @post.background_transition_select, {default: "default"},  class: 'form-control'
      %div
        = t.label :s_parallaxBackgroundImage, "Parallax background image"
        = t.text_field :s_parallaxBackgroundImage, default: "", placeholder: "image url", class: 'form-control'
      %div
        = t.label :s_parallaxBackgroundSize, "Parallax background size"
        = t.text_field :s_parallaxBackgroundSize, default: "", placeholder: "eg. 2100px 900px", class: 'form-control'
%script
  var editor = ace.edit("editor");
  var textarea = $('textarea[name="post[content]"]').hide();
  editor.setTheme("ace/theme/monokai");
  editor.getSession().setMode("ace/mode/markdown");
  editor.setValue(textarea.val(), -1);
  editor.getSession().on('change', function(){
  textarea.val(editor.getSession().getValue());
  });

app/views/admin/posts/_ppt.html.haml
- posts.each do |post|
  .col-sm-3
    = link_to image_tag(post.cover_page_url, {height: 160, width:210}), admin_user_post_path(current_user, post)
    %p
    %p    
      = link_to 'Edit', edit_admin_user_post_path(current_user, post), class: ['btn', 'btn-default']
      = link_to 'Publish', change_status_admin_user_post_path(current_user, post, status: 1), method: :put, class: ['btn', 'btn-default'], data: { confirm: t('model.post.publish.confirm') }, disabled: post.open? ? true : false
      -#= link_to 'Share', edit_admin_user_post_path(current_user, post), class: ['btn', 'btn-default']
      = link_to 'Delete', admin_user_post_path(current_user, post), method: :delete, class: ['btn', 'btn-default'], data: { confirm: t('model.post.delete.confirm') }

app/views/admin/posts/edit.html.haml
.alert.alert-info
  NOTICE: Editing post

- if @post.errors.any?
  = render partial: 'alert_error', locals: { model: @post }
= form_for :post, method: 'put', url: admin_user_post_path, html: { class: 'form-horizontal', role: 'form' } do |t|
  = render partial: 'form', locals: { t: t}
  .form-group
    %center
      = t.submit 'save', class: ['btn', 'btn-lg', 'btn-primary']
      = link_to t('model.post.show_ppt'), admin_user_post_path, class: ['btn', 'btn-lg', 'btn-info']

app/views/admin/posts/index.html.haml
%br
%br
%br
.alert.alert-success
  .glyphicon.glyphicon-user
  My PPT
= render 'layouts/messages'

- cache(cache_key_for_posts) do
  - if @posts.present?
    - @posts.each_slice(4) do |sub_posts|
      .container
        .row= render partial: 'ppt', locals: { posts: sub_posts}    
        %hr/

  %center= paginate @posts

.container
  .pull-right= link_to 'Add New', new_admin_user_post_path(current_user), class: ['btn', 'btn-lg', 'btn-warning']

app/views/admin/posts/new.html.haml
.alert.alert-info
  %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
  = content_tag :div, t('model.post.tips')

- if @post.errors.any?
  = render partial: 'alert_error', locals: { model: @post }
= form_for :post, method: 'post', url: admin_user_posts_path(current_user), html: { class: 'form-horizontal', role: 'form' } do |t|
  = render partial: 'form', locals: { t: t}
  .form-group
    %center
      = t.submit 'save', class: ['btn', 'btn-lg', 'btn-primary']

app/views/admin/posts/show.html.haml
= @post.content.html_safe