config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: "welcome#index"
  get 'welcome/about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: 'users/passwords',
  }

  resources :posts do
    member do
      get 'simple'
    end
  end

  namespace :admin do
    resources :users do
      resources :posts do
        member do 
          put 'change_status'
        end
      end
    end
  end

end

app/views/layouts/_footer.html.haml
.footer
  %p
    Driven by
    %a{:href => "http://www.slidemark.net"} SlideMark
  %p
    %a{:href => "#"} Back to top

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == 'notice' ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.navbar-wrapper
  .container
    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'SlideMark', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          - if user_signed_in?
            %ul.nav.navbar-nav
              %li= link_to t('navi.ppt'), admin_user_posts_path(current_user), class: 'active'
              %li= link_to t('navi.help'), welcome_about_path
              %li
                %input#inputSearch.form-control{:placeholder => "Search", :type => "search"}/
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "#{current_user.email}#{t('navi.home')}", admin_user_posts_path(current_user)
              %li= link_to t('navi.logout.title'), destroy_user_session_path, method: :delete, data: { confirm: t('navi.logout.confirm') }
          - else
            %ul.nav.navbar-nav
              %li= link_to t('navi.ppt'), new_user_session_path, class: 'active'
              %li= link_to t('navi.help'), welcome_about_path
            = form_for(:user, url: session_path(:user), html: { class: ['navbar-form', 'navbar-right'], role: 'form'}) do |t|
              .form-group
                = t.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email'
              .form-group
                = t.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password'
              .form-group
                = t.submit t('navi.signin'), class: ['btn-success', 'btn']
                = link_to t('navi.regist'), new_user_registration_path, class: ['btn-link', 'btn']

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'SlideMark'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Share your slide'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    %script{src: "/assets/src/ace.js", type: "text/javascript", charset: "utf-8"}
    = csrf_meta_tags
    %style#holderjs-style{:type => "text/css"}
  %body{:style => ""}
    <div id="fb-root"></div>
    <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));</script>
    <script src="//platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
    = render 'layouts/navigation'
    = yield
= render 'layouts/footer'
= debug(params) if Rails.env.development?

app/views/layouts/ppt.html.haml
!!!
%html
  %head
    -# update this for chinese encoding problem
    %title= content_for?(:title) ? yield(:title) : 'PPt'
    %meta{content: @post.user.email, :name => "author"}
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}
    %meta{:content => "black-translucent", :name => "apple-mobile-web-app-status-bar-style"}
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    %link{:href => "/assets/reveal/css/reveal.min.css", :rel => "stylesheet"}
    %link#theme{:href => "/assets/reveal/css/theme/default.css", :rel => "stylesheet"}
    / For syntax highlighting
    %link{:href => "/assets/reveal/lib/css/zenburn.css", :rel => "stylesheet"}
    / If the query includes 'print-pdf', include the PDF print sheet
    :javascript
      if( window.location.search.match( /print-pdf/gi ) ) {
      	var link = document.createElement( 'link' );
      	link.rel = 'stylesheet';
      	link.type = 'text/css';
      	link.href = '/assets/reveal/css/print/pdf.css';
      	document.getElementsByTagName( 'head' )[0].appendChild( link );
      }
    /[if lt IE 9]
      <script src="/assets/reveal/lib/js/html5shiv.js"></script>
  %body
    .reveal
      / Any section element inside of this container is displayed as a slide
      .slides
        %section{"data-markdown" => "", "data-separator" => "^---$", "data-vertical" => "^--$"}
          %script{:type => "text/template"}
            = yield
    %script{:src => "/assets/reveal/lib/js/head.min.js"}
    %script{:src => "/assets/reveal/js/reveal.min.js"}
    :javascript
      Reveal.initialize({
        controls: #{@post.s_controls},
        progress: #{@post.s_progress},
        slideNumber: #{@post.s_slideNumber},
        history: #{@post.s_history},
        keyboard: #{@post.s_keyboard},
        overview: #{@post.s_overview},
        center: #{@post.s_center},
        touch: 1,
        loop: #{@post.s_loop},
        rtl: #{@post.s_rtl},
        fragments: #{@post.s_fragments},
        embedded: #{@post.s_embedded},
        autoSlide: #{@post.s_autoSlide},
        autoSlideStoppable: #{@post.s_autoSlideStoppable},
        mouseWheel: #{@post.s_mouseWheel},
        hideAddressBar: #{@post.s_hideAddressBar},
        previewLinks: #{@post.s_previewLinks},
        viewDistance: #{@post.s_viewDistance},
        transition: "#{@post.s_transition}",
        transitionSpeed: "#{@post.s_transitionSpeed}",
        theme: "#{@post.s_theme}",
        backgroundTransition: "#{@post.s_backgroundTransition}",
        parallaxBackgroundImage: "#{@post.s_parallaxBackgroundImage}",
        parallaxBackgroundSize: "#{@post.s_parallaxBackgroundSize}",
      	dependencies: [
      		{ src: '/assets/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
      		{ src: '/assets/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
      		{ src: '/assets/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
      		{ src: '/assets/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
      		{ src: '/assets/reveal/plugin/zoom-js/zoom.js', async: true, condition: function() { return !!document.body.classList; } },
      		{ src: '/assets/reveal/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } }
      	]
      });

app/views/layouts/signin.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Myapp'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Myshop'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %style#holderjs-style{:type => "text/css"}
  %body{:style => ""}
    = render 'layouts/navigation'
    %br
    %br
    %br
    %br
    .container
      - if resource.present? && resource.errors.any?
        = render partial: 'alert_error', locals: { model: resource }
      = render 'layouts/messages'
      = yield
= render 'layouts/footer'
= debug(params) if Rails.env.development?

app/views/layouts/simple.html.haml
!!!
%html
  %head
    -# update this for chinese encoding problem
    %title= content_for?(:title) ? yield(:title) : 'PPt'
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}
    %meta{:content => "black-translucent", :name => "apple-mobile-web-app-status-bar-style"}
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    %link{:href => "/assets/reveal/css/reveal.min.css", :rel => "stylesheet"}
    %link#theme{:href => "/assets/reveal/css/theme/default.css", :rel => "stylesheet"}
    / For syntax highlighting
    %link{:href => "/assets/reveal/lib/css/zenburn.css", :rel => "stylesheet"}
    /[if lt IE 9]
      <script src="/assets/reveal/lib/js/html5shiv.js"></script>
  %body
    .reveal
      / Any section element inside of this container is displayed as a slide
      .slides
        %section{"data-markdown" => "", "data-separator" => "^---$", "data-vertical" => "^--$"}
          %script{:type => "text/template"}
            = yield
    %script{:src => "/assets/reveal/lib/js/head.min.js"}
    %script{:src => "/assets/reveal/js/reveal.min.js"}
    :javascript
      Reveal.initialize({
        controls: 0,
        progress: 0,
        slideNumber: 0,
        history: 0,
        center: #{@post.s_center},
        theme: "#{@post.s_theme}",
        parallaxBackgroundImage: "#{@post.s_parallaxBackgroundImage}",
        parallaxBackgroundSize: "#{@post.s_parallaxBackgroundSize}",
      	dependencies: [
      		{ src: '/assets/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
      		{ src: '/assets/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
      		{ src: '/assets/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
      		{ src: '/assets/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
      		{ src: '/assets/reveal/plugin/zoom-js/zoom.js', async: true, condition: function() { return !!document.body.classList; } },
      		{ src: '/assets/reveal/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } }
      	]
      });